version 2.1
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      -checkout
   
      -run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.38.9/terragrunt_linux_arm64
      -run: mv terragrunt_linux_arm64 terragrunt
      -run: chmod u+x terragrunt
      -run: mv terragrunt /usr/local/bin/terragrunt
