# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1

executors:
  terraform_executor:
    docker:
      - image: << parameters.docker_image >>
    working_directory: << parameters.workspace_root >>
    parameters:
      docker_image:
        default: khultman/cci-terraform:latest
        description: The docker image to use
        type: string
      workspace_root:
        type: string
        description: The working directory for terraform & terragrunt
        default: /terraform

commands:
  add_vcs_provider_to_ssh_known_hosts:
    description: Add VCS providers (github.com && bitbucket.org) to ~/.ssh/known_hosts
    steps:
      - run: mkdir ~/.ssh
      - run: ssh-keyscan -t rsa github.com ~/.ssh/known_hosts
  attach_terraform_workspace:
    description: Attach the workspace to the docker image
    parameters:
      workspace_root:
        type: string
        description: The working directory for terraform & terragrunt
        default: /terraform
    steps:
      - attach_workspace:
          at: << parameters.workspace_root >>
  terragrunt_plan_all:
    description: Run terragrunt plan-all --terragrunt-non-interactive
    steps:
      - run: terragrunt plan-all --terragrunt-non-interactive
  terragrunt_validate_all:
    description: Run terragrunt validate-all
    steps:
      - run: terragrunt validate-all
  terragrunt_apply_all:
    description: Run terragrunt apply-all --terragrunt-non-interactive
    steps:
      - run: terragrunt apply-all --terragrunt-non-interactive
  set_workspace_persistance:
    description: Set workspace persistence
    parameters:
      workspace_root:
        type: string
        description: The working directory for terraform & terragrunt
        default: /terraform
    steps:
      - persist_to_workspace:
          root: << parameters.workspace_root >>
          paths:
            - .
            - .*
            - .terraform
            - tfplan

jobs:
  checkout:
    executor:
      name: terraform_executor
    steps:
      - attach_terraform_workspace
      - add_vcs_provider_to_ssh_known_hosts
      - checkout
      - set_workspace_persistance

  validate_infrastructure:
    executor:
      name: terraform_executor
    steps:
      - attach_terraform_workspace
      - add_vcs_provider_to_ssh_known_hosts
      - terragrunt_validate_all
      - set_workspace_persistance

  plan_infrastructure:
    executor:
      name: terraform_executor
    steps:
      - attach_terraform_workspace
      - add_vcs_provider_to_ssh_known_hosts
      - terragrunt_plan_all
      - set_workspace_persistance

  apply_infrastructure:
    executor:
      name: terraform_executor
    steps:
      - attach_terraform_workspace
      - add_vcs_provider_to_ssh_known_hosts
      - terragrunt_apply_all




